language: java
jdk: openjdk12

install:
 - mvn clean install -Dgpg.skip=true
 
cache:
  directories:
  - $HOME/.m2
  
notifications:
  email:  
    recipients:
    - pierre.huber@agilitest.com
    - gabriel.gil@agilitest.com
    - anthony.dhierre@agilitest.com
    on_success: always  
    on_failure: always