language: java
jdk: openjdk14
branches:
  only:
  - master
install:
- mvn install -Dgpg.skip=true
cache:
  directories:
  - "$HOME/.m2"
script:
  - mvn clean package
  - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print "Covered code -> ",covered,"/",instructions,"\nCoverage -> ",100*covered/instructions,"%" }' target/site/jacoco/jacoco.csv > $TRAVIS_BUILD_DIR/target/site/jacoco/cover-status.txt
notifications:
  slack:
    matrix:
    - agilitest:89arTDhysVkKJ7TGJ2qw6Xwv
    rooms:
      secure: GblO7S/YBWEg+pHrL3a4Sgkmps7SlH3HAi++J4t5oSJ+cLjMBAtpiLVmUYZkRySSnYKRPfD8tJZfQKF9nxu1PfSyEkEhUl/4xWAuRaeK5apyLBf19Rzg+t6dYJg4FZN0TXA6VT3QvNmKDSUSxXDJ9XMJDhg8FTLdmIPzhRfHVB4CB1+vsuU1OH44BTTS7xuP7g8oSjkPDooyYo44fOFS+NMibE0G8xbbLH3qXudBEU6IGc/zNoAhcr8hTTQ4yHGaQnsGjZrQzv5x+VvUQAGxfjMypi+tES6GRI1jG6ZEGlkJf/I/xjWHptnqMsXS7tvsawFvruLKBwwkjYl/B9G1nRU8tISXHnoCvtHFmr4kc4m/BFAMGkyt9B3X/fQTl0ewBw0ZDTBFSjjP/RDo5ahzeT3cJXFQQZQULPLMT+ubt0UXUoX66toHm4WMaHagTVBsqSmS4esRdmgy2shpVUboi1gPhuwD/3SFnL65+hoazTBn7pQipjo+fGrehtb2+J+w/0TUbDmD6TTnmSmxgJDpiK5gpOfNw5huYXMAz+hMMCPcSnWi7dVdkMHfiqJ6eyuipKmccEBRv8OelMXXQtTgy/KQj3z0Tg7i+U/k9jGTmo3f+TNsEMzQWsNKv9ka/IJbAymmwi7pam0cjoXp/zcsjKuaL9WI1eEwdRVscXTqjZ8=
    on_success: always
    on_failure: always
    template:
      - "Project : *%{repository_name}*  _(build <%{build_url}|#%{build_number}>, commit <%{compare_url}|%{commit}>)_"
      - "Status: %{result}  _(executed in : %{duration})_"
      - "Branch : %{branch}  _(<https://raw.githubusercontent.com/pierrehub2b/actiontestscript/gh-pages/cover-status.txt|test coverage>)_"
      - "Commit : %{author}  `%{commit_message}`"
deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: $TRAVIS_BUILD_DIR/target/site/jacoco
    skip_cleanup: 'true'
