language: java
jdk: openjdk10

install:
 - mvn install -Dgpg.skip=true
 
cache:
  directories:
  - $HOME/.m2
  
 notifications:
  email:
    - pierre.huber@agilitest.com
    - gabriel.gil@agilitest.com
    - anthony.dhierre@agilitest.com