language: java
jdk: openjdk12

install:
 - mvn clean install -Dgpg.skip=true
 
cache:
  directories:
  - $HOME/.m2
    
deploy:
  provider: rubygems
  api_key: "YOUR API KEY"
  
notifications:
  slack: agilitest:89arTDhysVkKJ7TGJ2qw6Xwv