language: java
jdk: openjdk12

install:
 - mvn clean install -Dgpg.skip=true
 
cache:
  directories:
  - $HOME/.m2
  
notifications:
  email:  
    recipients:
    -  pierrehuber@yahoo.com
    -  gabriel.gil@outlook.fr
    -  anthony.dhierre@agilitest.com
    on_success: always  
    on_failure: always